
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Mar 12 14:11:47 EDT 2020
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class A5Sym{
  /* terminals */
  public static final int TIMES = 11;
  public static final int READ = 24;
  public static final int SEMICOLON = 20;
  public static final int ELSE = 17;
  public static final int PLUS = 2;
  public static final int RPAREN = 10;
  public static final int INT = 8;
  public static final int RETURN = 25;
  public static final int END = 6;
  public static final int IDENTIFIER = 15;
  public static final int IF = 16;
  public static final int LPAREN = 22;
  public static final int WRITE = 23;
  public static final int BEGIN = 5;
  public static final int QUOTE = 4;
  public static final int STRING = 26;
  public static final int COMMA = 21;
  public static final int ASSIGNEQU = 13;
  public static final int NUMBER = 19;
  public static final int NEQUAL = 18;
  public static final int EOF = 0;
  public static final int DIVIDE = 12;
  public static final int MAIN = 7;
  public static final int MINUS = 3;
  public static final int error = 1;
  public static final int REAL = 9;
  public static final int EEQUAL = 14;
}

